server:
  port: 9090
spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
      routes:
        - id: EVENT-SERVICE
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/api/events/**, /api/categories/**
          filters:
            - name: CircuitBreaker
              args:
                name: eventServiceCB
                fallbackUri: forward:/eventServiceFallback
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
                redis-rate-limiter.requestedTokens: 1
        - id: VENUE-SERVICE
          uri: lb://VENUE-SERVICE
          predicates:
            - Path=/api/venues/**
          filters :
            - name : CircuitBreaker
              args :
                name : venueServiceCB
                fallbackUri : forward:/venueServiceFallback
            - name : RequestRateLimiter
              args :
                redis-rate-limiter.replenishRate : 1
                redis-rate-limiter.burstCapacity : 1
                redis-rate-limiter.requestedTokens : 1
    discovery :
      enabled : true