server:
  port: 9090
spring:
  application:
    name: API-GATEWAY
  config:
    import:
      - configserver:http://localhost:9296
  cloud:
    gateway:
      routes:
        - id: EVENT-SERVICE
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/api/events**, /api/categories**
        - id: VENUE-SERVICE
          uri: lb://VENUE-SERVICE
          predicates:
            - Path=/api/venues**
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users**
    discovery:
      enabled: true